apiVersion: v1
data:
  mongo-user: bWFuZ28tdXNlcg==
  mongo-pwd: bWFuZ28tcHdk
kind: Secret
metadata:
  
  creationTimestamp: 2022-04-22T18:41:56Z
  name: mongo-secret
  namespace: default
  #resourceVersion: "164619"
  #uid: cfee02d6-c137-11e5-8d73-42010af00002
type: Opaque
